# buildZxScript { pname, version, src, entrypoint, ... }
#
# Single-step packager for zx (google/zx) TypeScript scripts.
#
# Three usage tiers:
#
#   Tier 1 — zero-config (just zx):
#     buildZxScript { pname = "my-tool"; src = ./.; }
#
#   Tier 2 — extra npm deps (zero-transitive-dep packages):
#     buildZxScript {
#       pname = "my-tool"; src = ./.;
#       extraDeps = {
#         "chalk@5.4.1" = pkgs.fetchurl {
#           url = "https://registry.npmjs.org/chalk/-/chalk-5.4.1.tgz";
#           hash = "sha512-...";  # nix-prefetch-url <url>
#         };
#       };
#     }
#
#   Tier 3 — full override (deps with transitive trees):
#     buildZxScript {
#       pname = "my-tool"; src = ./.;  # src must contain bun.lock
#       bunNix = ./bun.nix;            # generated by bun2nix
#     }
#
# The wrapper unsets LD_LIBRARY_PATH to prevent devshell library leaks
# (see amarbel-llc/bun#4).
{ pkgs, lib, bun, fetchBunDeps }:

let
  # -- Vendored zx dependency --
  # Bump: update zxVersion and zxHash together.
  zxVersion = "8.8.5";
  zxHash = "sha512-SNgDF5L0gfN7FwVOdEFguY3orU5AkfFZm9B5YSHog/UDHv+lvmd82ZAsOenOkQixigwH2+yyH198AwNdKhj+RA==";
  zxDep = {
    "zx@${zxVersion}" = pkgs.fetchurl {
      url = "https://registry.npmjs.org/zx/-/zx-${zxVersion}.tgz";
      hash = zxHash;
    };
  };

  # -- Helpers --

  # Map a .ts/.tsx/.mts/.cts basename to .js
  tsToJs =
    name:
    lib.replaceStrings
      [ ".ts" ".tsx" ".mts" ".cts" ]
      [ ".js" ".js" ".js" ".js" ]
      (builtins.baseNameOf name);

  # Parse "name@version" into { name, version }.
  parseDepKey =
    key:
    let
      # Split on last @ (handles scoped packages like @scope/pkg@1.0.0)
      parts = lib.splitString "@" key;
      len = builtins.length parts;
      # For "@scope/pkg@1.0.0" → ["" "scope/pkg" "1.0.0"]
      # For "pkg@1.0.0" → ["pkg" "1.0.0"]
      name =
        if len == 3 then
          "@${builtins.elemAt parts 1}"
        else
          builtins.elemAt parts 0;
      version = builtins.elemAt parts (len - 1);
    in
    { inherit name version; };

  # Generate synthetic package.json content from a dep attrset.
  mkPackageJson =
    pname: allDeps:
    let
      deps = lib.mapAttrs' (
        key: _:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name parsed.version
      ) allDeps;
    in
    builtins.toJSON {
      name = pname;
      dependencies = deps;
    };

  # Generate synthetic bun.lock content from a dep attrset.
  # Each dep becomes a lockfile package tuple:
  #   [resolved_spec, "", {}, integrity_hash]
  mkBunLock =
    pname: allDeps:
    let
      deps = lib.mapAttrs' (
        key: _:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name parsed.version
      ) allDeps;

      packages = lib.mapAttrs' (
        key: dep:
        let
          parsed = parseDepKey key;
        in
        lib.nameValuePair parsed.name [
          key
          ""
          { }
          dep.outputHash
        ]
      ) allDeps;
    in
    builtins.toJSON {
      lockfileVersion = 1;
      workspaces = {
        "" = {
          name = pname;
          dependencies = deps;
        };
      };
      inherit packages;
    };

  # Create a wrapper script for a single binary.
  mkWrapper =
    {
      name,
      bundle,
      jsFile,
      runtimeInputs ? [ ],
      runtimeEnv ? { },
    }:
    let
      envExports = lib.concatStringsSep "\n" (
        lib.mapAttrsToList (k: v: "export ${k}=${lib.escapeShellArg v}") runtimeEnv
      );
      pathSetup = lib.optionalString (runtimeInputs != [ ]) ''
        export PATH="${lib.makeBinPath runtimeInputs}:$PATH"
      '';
    in
    pkgs.writeShellScriptBin name ''
      ${envExports}
      ${pathSetup}
      unset LD_LIBRARY_PATH
      exec ${bun}/bin/bun ${bundle}/${jsFile} "$@"
    '';

in
{
  buildZxScript =
    {
      pname,
      version ? "0.0.0",
      src,
      entrypoint ? "index.ts",
      bunNix ? null,
      bunBuildFlags ? [ ],
      runtimeInputs ? [ ],
      runtimeEnv ? { },
      extraDeps ? { },
      bunfigPath ? null,
      npmrcPath ? null,
      overrides ? { },
      ...
    }:
    let
      # Tier 3: full override via bunNix
      useBunNix = bunNix != null;

      # Tiers 1 & 2: merge vendored zx with extraDeps
      allDeps = zxDep // extraDeps;

      # -- Cache --
      # Tier 3: use fetchBunDeps (same as buildBunBinary)
      # Tiers 1&2: symlinkJoin of fetchurl tarballs
      cache =
        fetchBunDeps {
          bunNix =
            if useBunNix then
              bunNix
            else
              # Programmatic bunNix: ignore injected fetchurl, return
              # pre-fetched tarballs directly.
              { ... }:
              allDeps;
          inherit bunfigPath npmrcPath overrides;
        };

      # -- Synthetic files (tiers 1 & 2 only) --
      syntheticPackageJson = pkgs.writeText "${pname}-package.json" (mkPackageJson pname allDeps);
      syntheticBunLock = pkgs.writeText "${pname}-bun.lock" (mkBunLock pname allDeps);

      # -- Bundle derivation --
      bundle = pkgs.stdenvNoCC.mkDerivation {
        pname = "${pname}-bundle";
        inherit version src;

        nativeBuildInputs = [ bun ];

        buildPhase =
          ''
            runHook preBuild

            export BUN_INSTALL_CACHE_DIR=$(mktemp -d)
          ''
          + ''
            cp -r ${cache}/share/bun-cache/. "$BUN_INSTALL_CACHE_DIR"
          ''
          + (
            if useBunNix then
              # Tier 3: src contains bun.lock
              ''
                bun install --frozen-lockfile --linker=isolated
              ''
            else
              # Tiers 1&2: inject synthetic package.json + bun.lock
              ''
                cp ${syntheticPackageJson} package.json
                cp ${syntheticBunLock} bun.lock
                bun install --frozen-lockfile --linker=isolated
              ''
          )
          + ''
            mkdir -p $out
            bun build ${lib.escapeShellArg entrypoint} \
              --target=bun \
              --format=esm \
              --outdir=$out \
              ${lib.escapeShellArgs bunBuildFlags}

            runHook postBuild
          '';

        dontInstall = true;
        dontFixup = true;
      };
    in
    mkWrapper {
      name = pname;
      inherit bundle runtimeInputs runtimeEnv;
      jsFile = tsToJs entrypoint;
    };
}
